---
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: quay.io/redhat-appstudio/pipeline-service-exporter
    newName: quay.io/redhat-appstudio/pipeline-service-exporter
    newTag: 62dd8400c94ac2f2b3cc41c910d0e4111e470e11

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
