---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-metrics-exporter-service
  namespace: openshift-pipelines
  labels:
    app: pipeline-metrics-exporter
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: pipeline-metrics-exporter
  ports:
    - name: metrics
      port: 9117
      targetPort: 9117
      protocol: TCP
