---
check: []
compact: false
evaluate-variables: true
framework:
  - kubernetes
  - dockerfile
  - github_actions
  - kustomize
skip-download: false
output: cli
quiet: true
skip-check:
  # skip HEALTHCHECK instructions check
  - CKV_DOCKER_2
skip-fixes: true
soft-fail: true
