---
apiVersion: v1
kind: Pod
metadata:
  name: ci-runner
  namespace: ci-runner
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  automountServiceAccountToken: false
  containers:
    - name: ci-runner
      image: quay.io/redhat-pipeline-service/ci-runner:main
      imagePullPolicy: Always
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
          ephemeral-storage: "2Gi"
        limits:
          ephemeral-storage: "2Gi"
      command:
        - /bin/bash
        - -c
        - sleep 3600
      securityContext:
        privileged: true
      volumeMounts:
        - name: pull-secret
          mountPath: "/run/user/0/containers/"
          readOnly: true
        - name: ci-runner-storage
          mountPath: "/source"
  volumes:
    - name: pull-secret
      secret:
        secretName: pull-secret
    - name: ci-runner-storage
      persistentVolumeClaim:
        claimName: ci-runner-pvc
