---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allow-argocd-to-manage.yaml
  - openshift-operator.yaml
  - tekton-config.yaml
  # Once we disable RBAC creation in Tekton-config, SCC will not be created automatically
  # by Openshift-Pipelines operator
  - pipelines-scc.yaml
