apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watcher
rules:
  # Watcher needs to be able to create new and update existing results.
  - apiGroups: ["results.tekton.dev"]
    resources: ["logs", "results", "records"]
    verbs: ["create", "get", "update"]
  # Needed to read results and update annotations with Result ID.
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "taskruns"]
    verbs: ["get", "list", "patch", "update", "watch", "delete"]
  # Watcher currently get config from APISever, so will
  # fail to start if it does not have this permission.
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["get", "list", "watch"]
  # Required to read logs, when logs API is enabled
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines"]
    verbs: ["get"]
  # Required for enabling leader election.
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  # Watcher needs to be able to verify incoming auth tokens.
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  # Watcher needs to be able to use RBAC to verify user authorization.
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
