---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../operator/gitops/argocd/pipeline-service/tekton-results/base

patchesStrategicMerge:
  - minio-create-bucket.yaml
  - minio-tls.yaml
